server {
    listen 80;
    server_name polybot.mssmart.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name polybot.mssmart.id;

    ssl_certificate /etc/nginx/ssl/mssmart.pem;
    ssl_certificate_key /etc/nginx/ssl/mssmart.key;

    location / {
        proxy_pass http://127.0.0.1:47302;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 30s;
    }
}
